/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

import { createClient as createSupabaseClient, SupabaseClient } from '@supabase/supabase-js'

export const projectId = "bitcsqyvattyxydlmlkb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpdGNzcXl2YXR0eXh5ZGxtbGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Mjg4MjUsImV4cCI6MjA3NDUwNDgyNX0.aTIMLFn4DBdyUdrzQ5NE_8Z7sY_YKJiaPApBC4-66uI"

const supabaseUrl = `https://${projectId}.supabase.co`

// Singleton Supabase client instance
let supabaseClient: SupabaseClient | null = null;

// Create a singleton Supabase client to avoid multiple instances
export const createClient = (): SupabaseClient => {
  // Return existing client if already created
  if (supabaseClient) {
    return supabaseClient;
  }

  // Create new client instance only if needed
  supabaseClient = createSupabaseClient(supabaseUrl, publicAnonKey, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false
    },
    global: {
      headers: {
        'X-Client-Info': 'firefly-emergency-dashboard'
      }
    }
  });

  return supabaseClient;
}

// Get existing client instance (for debugging)
export const getExistingClient = (): SupabaseClient | null => {
  return supabaseClient;
}

// Reset client instance (for debugging/testing)
export const resetClient = (): void => {
  if (supabaseClient) {
    console.log('🔄 Resetting Supabase client instance');
    supabaseClient = null;
  }
}